### ISSUE TITLE
Date of uploaded files incorrect

### ISSUE THREAD

**Issue by Silanael** [ardriveapp/ardrive-web#247] opened 2021-10-24 16:06 UTC
The web interface doesn't save the filesystem's "modified" date of a file, instead using current time for the ArFS metadata (.json?). This can be considered as loss of information and should be fixed so that the original file date is preserved. Or might it be yet another limitation of the platform?

This issue seems to be limited to ardrive-web - the CLI v1 properly stores the original file date.

Would be nice to get this fixed for the upcoming new version.

**Comment by agsuy** [comment] 2021-11-03 19:58
We were unable to reproduce this.

Can you share the steps you where following in detail?

**Comment by Silanael** [comment] 2021-11-03 20:06
1) Find a file from your local filesystem that has last modified date something other than today (a file that was created in the past).
2) Drag the file into the web UI for upload
3) Open file info for the uploaded file
4) Observe that all three dates (last modified, last updated, date created) are the same, each displaying the date upload took place instead of the original file's last modified date.
5) ???
6) Profit

Observed using Manjaro Linux, GNOME 40.4.0, X11, Chromium 94.0.4606.81

**Comment by agsuy** [comment] 2022-01-26 15:43
Fixed as of 1.5.0, closing.

**Closed by agsuy** 2022-01-26 15:43 UTC
Labels: Accepted, Bug
