### ISSUE TITLE
`flutter pub get` doesn't work

### ISSUE THREAD

**Issue by vporton** [ardriveapp/ardrive-web#363] opened 2022-02-15 22:34 UTC
```
$ git status 
On branch dev
Your branch is up to date with 'origin/dev'.

nothing to commit, working tree clean
$ flutter pub get
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Warning
──────────────────────────────────────────────────────────────────────────────
Your Flutter application is created using an older version of the Android
embedding. It is being deprecated in favor of Android embedding v2. Follow the
steps at

https://flutter.dev/go/android-project-migration

to migrate your project. You may also pass the --ignore-deprecation flag to
ignore this check and continue with the deprecated v1 embedding. However,
the v1 Android embedding will be removed in future versions of Flutter.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
The detected reason was:

  /home/porton/Projects/ardrive-web/android/app/src/main/AndroidManifest.xml uses `android:name="io.flutter.app.FutterApplication"`
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Because test >=1.16.7 <1.17.0 depends on test_api 0.3.0 and test >=1.17.0 <1.17.6 depends on test_api 0.4.0, test >=1.16.7 <1.17.6 requires test_api 0.3.0 or 0.4.0.
And because test >=1.17.6 <1.17.10 depends on test_api 0.4.1, test >=1.16.7 <1.17.10 requires test_api 0.3.0 or 0.4.0 or 0.4.1.
And because test >=1.17.10 <1.17.11 depends on test_api 0.4.2 and test >=1.17.11 <1.18.0 depends on test_api 0.4.3, test >=1.16.7 <1.18.0 requires test_api 0.3.0 or 0.4.0 or 0.4.1 or 0.4.2 or 0.4.3.
And because test >=1.18.0 <1.18.1 depends on test_api 0.4.4 and test >=1.18.1 <1.19.0 depends on test_api 0.4.5, test >=1.16.7 <1.19.0 requires test_api 0.3.0 or 0.4.0 or 0.4.1 or 0.4.2 or 0.4.3 or 0.4.4 or 0.4.5.
And because test >=1.19.0 <1.19.3 depends on test_api 0.4.6 and test >=1.19.3 <1.19.4 depends on test_core 0.4.8, test >=1.16.7 <1.19.4 requires test_core 0.4.8 or test_api 0.3.0 or 0.4.0 or 0.4.1 or 0.4.2 or 0.4.3 or 0.4.4 or 0.4.5 or 0.4.6.
And because test >=1.20.0 depends on test_api 0.4.9 and test >=1.19.4 <1.20.0 depends on test_core 0.4.9, test >=1.16.7 requires test_core 0.4.8 or 0.4.9 or test_api 0.3.0 or 0.4.0 or 0.4.1 or 0.4.2 or 0.4.3 or 0.4.4 or 0.4.5 or 0.4.6 or 0.4.9.
Because json_serializable ^4.0.1 depends on analyzer >=0.41.2 <2.0.0 and test_core >=0.4.5 <0.4.10 depends on analyzer ^2.4.0, json_serializable ^4.0.1 is incompatible with test_core >=0.4.5 <0.4.10.
Thus, if json_serializable ^4.0.1 and test >=1.16.7 then test_api 0.3.0 or 0.4.0 or 0.4.1 or 0.4.2 or 0.4.3 or 0.4.4 or 0.4.5 or 0.4.6 or 0.4.9.
And because ardrive depends on flutter_driver from sdk which depends on test_api 0.4.8, json_serializable ^4.0.1 is incompatible with test >=1.16.7.
So, because ardrive depends on both test ^1.16.8 and json_serializable ^4.1.0, version solving failed.
Running "flutter pub get" in ardrive-web...                             
pub get failed (1; So, because ardrive depends on both test ^1.16.8 and json_serializable ^4.1.0, version solving failed.)
```

**Comment by jdaev** [comment] 2022-02-15 23:41
Try using flutter version 2.8.1

**Comment by vporton** [comment] 2022-02-16 00:05
> Try using flutter version 2.8.1

With 2.8.1 the problem disappeared.

**Comment by agsuy** [comment] 2022-02-25 19:20
Works as intended, closing.

**Closed by agsuy** 2022-02-25 19:20 UTC
Labels: Works as intended
